# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch


# Create random tensor
tensor = torch.rand(7, 7)
tensor, tensor.shape

(tensor([[0.1394, 0.2582, 0.5283, 0.4466, 0.6057, 0.9690, 0.3518],
         [0.0677, 0.4113, 0.6338, 0.3833, 0.9607, 0.5962, 0.7378],
         [0.3699, 0.0074, 0.2806, 0.8905, 0.0996, 0.8842, 0.2968],
         [0.6114, 0.8181, 0.8337, 0.1850, 0.6934, 0.6385, 0.4890],
         [0.9228, 0.1229, 0.9129, 0.8798, 0.3673, 0.0056, 0.8089],
         [0.5337, 0.2308, 0.5678, 0.0407, 0.8480, 0.9759, 0.4447],
         [0.3648, 0.0925, 0.4613, 0.3602, 0.6298, 0.7923, 0.0492]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor2 = torch.rand(1, 7)

# Perform matrix multiplication 
mult = torch.matmul(tensor, tensor2.T)
mult, mult.shape

(tensor([[1.5373],
         [1.7504],
         [1.1838],
         [1.8080],
         [1.7429],
         [1.7575],
         [1.3503]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
# Create two random tensors
torch.manual_seed(0)
r1 = torch.rand(7, 7)
torch.manual_seed(0)
r2 = torch.rand(1, 7)

# Matrix multiply tensors
mult = torch.matmul(r1, r2.T)

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
# Check for access to GPU
print(torch.cuda.is_available())
# Create two random tensors on GPU
torch.manual_seed(1234)
t1 = torch.rand(size=(2,3), device='cuda')
torch.manual_seed(1234)
t2 = torch.rand(size=(2,3), device='cuda')
t1, t1.device, t2, t2.device

True


(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 device(type='cuda', index=0),
 tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 device(type='cuda', index=0))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [10]:
# Perform matmul on tensor_A and tensor_B
mult = torch.matmul(t1, t2.T)
mult

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [12]:
# Find max
print(f"Max: {mult.max()}")
# Find min
print(f"Min: {mult.min()}")


Max: 1.4577524662017822
Min: 0.8358409404754639


### 9. Find the maximum and minimum index values of the output of 7.

In [18]:
# Find arg max
print(f"Max: {mult.argmax()}")
# Find arg min
print(f"Min: {mult.argmin()}")
mult

Max: 3
Min: 1


tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.manual_seed(7)

# Create random tensor
t1 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
t2 = t1.squeeze()

# Print out tensors and their shapes
t1, t1.shape, t2, t2.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))